"""Add edit_count to pick_tokens and last_edited_at to picks

Revision ID: 25a72b2ede9d
Revises: e49c0c65e3db
Create Date: 2025-08-28 02:37:28.333978

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '25a72b2ede9d'
down_revision = 'e49c0c65e3db'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pick_tokens', schema=None) as batch_op:
        batch_op.add_column(sa.Column('edit_count', sa.Integer(), nullable=True))

    with op.batch_alter_table('picks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_edited_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('picks', schema=None) as batch_op:
        batch_op.drop_column('last_edited_at')

    with op.batch_alter_table('pick_tokens', schema=None) as batch_op:
        batch_op.drop_column('edit_count')

    # ### end Alembic commands ###
