"""Allow null and unique whatsapp numbers for players

Revision ID: 9354f06ff969
Revises: de94423099bd
Create Date: 2025-08-26 17:53:52.467171

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9354f06ff969'
down_revision = 'de94423099bd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('send_queue')
    with op.batch_alter_table('players', schema=None) as batch_op:
        batch_op.alter_column('whatsapp_number',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
        batch_op.create_unique_constraint(None, ['whatsapp_number'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('players', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.alter_column('whatsapp_number',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)

    op.create_table('send_queue',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('player_id', sa.INTEGER(), nullable=False),
    sa.Column('number', sa.VARCHAR(length=20), nullable=False),
    sa.Column('message', sa.TEXT(), nullable=False),
    sa.Column('status', sa.VARCHAR(length=20), nullable=True),
    sa.Column('attempts', sa.INTEGER(), nullable=True),
    sa.Column('last_error', sa.TEXT(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
