"""Add cycle and postponement fields

Revision ID: c16973330891
Revises: 25a72b2ede9d
Create Date: 2025-09-06 18:44:41.485025

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c16973330891'
down_revision = '25a72b2ede9d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reminder_schedules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('round_id', sa.Integer(), nullable=False),
    sa.Column('reminder_type', sa.String(length=20), nullable=False),
    sa.Column('scheduled_time', sa.DateTime(), nullable=False),
    sa.Column('sent_at', sa.DateTime(), nullable=True),
    sa.Column('is_sent', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ),
    sa.ForeignKeyConstraint(['round_id'], ['rounds.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('picks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('auto_assigned', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('auto_reason', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('postponed_event_id', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('announcement_time', sa.DateTime(), nullable=True))

    with op.batch_alter_table('rounds', schema=None) as batch_op:
        batch_op.add_column(sa.Column('first_kickoff_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('special_measure', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('special_note', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('cycle_number', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rounds', schema=None) as batch_op:
        batch_op.drop_column('cycle_number')
        batch_op.drop_column('special_note')
        batch_op.drop_column('special_measure')
        batch_op.drop_column('first_kickoff_at')

    with op.batch_alter_table('picks', schema=None) as batch_op:
        batch_op.drop_column('announcement_time')
        batch_op.drop_column('postponed_event_id')
        batch_op.drop_column('auto_reason')
        batch_op.drop_column('auto_assigned')

    op.drop_table('reminder_schedules')
    # ### end Alembic commands ###
