"""Add pl_matchday to rounds table

Revision ID: de94423099bd
Revises: def52689b467
Create Date: 2025-08-21 19:48:44.894333

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'de94423099bd'
down_revision = 'def52689b467'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rounds', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pl_matchday', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rounds', schema=None) as batch_op:
        batch_op.drop_column('pl_matchday')

    # ### end Alembic commands ###
