"""Make whatsapp_number nullable and not unique

Revision ID: ee2fea6df2d5
Revises: de94423099bd
Create Date: 2025-08-26 18:18:25.004325

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ee2fea6df2d5'
down_revision = 'de94423099bd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_table('_alembic_tmp_players')
    with op.batch_alter_table('players', schema=None) as batch_op:
        batch_op.alter_column('whatsapp_number',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('players', schema=None) as batch_op:
        batch_op.alter_column('whatsapp_number',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)

    op.create_table('_alembic_tmp_players',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), nullable=False),
    sa.Column('whatsapp_number', sa.VARCHAR(length=20), nullable=True),
    sa.Column('status', sa.VARCHAR(length=20), nullable=True),
    sa.Column('unreachable', sa.BOOLEAN(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('whatsapp_number', name=op.f('uq_players_whatsapp_number'))
    )
    # ### end Alembic commands ###
